apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploymentName }}-ray-config
  namespace: {{ .Values.deploymentNamespace | default "default" }}
data:
  llm_deployment.py: |
{{ .Files.Get "files/llm_deployment.py" | indent 4 }}