{{- if .Values.huggingFaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentName }}-ray-hf-secret
  namespace: {{ .Values.deploymentNamespace | default "default" }}
data:
  hf_api_token: {{ .Values.huggingFaceToken | b64enc }}
{{- end }}