apiVersion: v1
kind: Service
metadata:
  name: {{ include "ray-llm-service.serveServiceName" . }}
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "ray-llm-service.serveServiceName" . }}
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "http"
    workspace.exalsius.ai/port-name: "http"
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8000
  selector:
    component.subtype: serve-endpoint
    ray.name: {{ include "ray-llm-service.deploymentName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ray-llm-service.dashboardServiceName" . }}
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "ray-llm-service.dashboardServiceName" . }}
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "http"
    workspace.exalsius.ai/port-name: "http"
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8265
  selector:
    component.type: head
    ray.name: {{ include "ray-llm-service.deploymentName" . }}