apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-ray-standalone-serve-service
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ .Values.deploymentName }}-ray-standalone-serve-service
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "http"
    workspace.exalsius.ai/port-name: "http"
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8000
  selector:
    component.subtype: serve-endpoint
    ray.name: {{ .Values.deploymentName }}-ray-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-ray-standalone-dashboard-service
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ .Values.deploymentName }}-ray-standalone-dashboard-service
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "http"
    workspace.exalsius.ai/port-name: "http"
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8265
  selector:
    component.type: head
    ray.name: {{ .Values.deploymentName }}-ray-service