apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ms.modelArtifacts.authSecretName }}
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.huggingfaceToken }}
  HF_TOKEN: {{ .Values.huggingfaceToken | b64enc }}
{{- end }}
{{- if .Values.inferenceApiKey }}
  VLLM_API_KEY: {{ .Values.inferenceApiKey | b64enc }}
{{- end }}