apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter-notebook.serviceName" . }}
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "jupyter-notebook.deploymentName" . }}
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "http"
    workspace.exalsius.ai/port-name: "http"
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8888
  selector:
    app: {{ include "jupyter-notebook.deploymentName" . }}