{{- if .Values.slurm.accounting.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "slurm.fullname" . }}-mariadb-operator-wait
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "slurm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mariadb-operator-wait
    app.kubernetes.io/part-of: {{ include "slurm.name" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "slurm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mariadb-operator-wait
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mariadb-operator-wait
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -euo pipefail
          
          echo "Waiting for MariaDB operator to be ready..."
          
          # Find MariaDB operator deployment dynamically
          echo "Searching for MariaDB operator deployment..."
          OPERATOR_DEPLOYMENT=""
          for i in {1..30}; do
            OPERATOR_DEPLOYMENT=$(kubectl get deployments -n {{ .Release.Namespace }} -o name | grep -i mariadb | grep -i operator | head -1 || true)
            if [ -n "${OPERATOR_DEPLOYMENT}" ]; then
              echo "Found operator deployment: ${OPERATOR_DEPLOYMENT}"
              break
            fi
            echo "Attempt ${i}/30: No MariaDB operator deployment found yet, waiting..."
            sleep 10
          done
          
          if [ -z "${OPERATOR_DEPLOYMENT}" ]; then
            echo "ERROR: MariaDB operator deployment not found after 5 minutes"
            echo "Available deployments:"
            kubectl get deployments -n {{ .Release.Namespace }}
            exit 1
          fi
          
          # Wait for operator pods to be ready
          echo "Waiting for MariaDB operator pods to be ready..."
          for i in {1..60}; do
            READY_PODS=$(kubectl get ${OPERATOR_DEPLOYMENT} -n {{ .Release.Namespace }} -o jsonpath='{.status.readyReplicas}' || echo "0")
            DESIRED_PODS=$(kubectl get ${OPERATOR_DEPLOYMENT} -n {{ .Release.Namespace }} -o jsonpath='{.spec.replicas}' || echo "0")
            
            if [ "${READY_PODS}" = "${DESIRED_PODS}" ] && [ "${READY_PODS}" != "0" ]; then
              echo "MariaDB operator pods are ready (${READY_PODS}/${DESIRED_PODS})"
              break
            fi
            
            echo "Attempt ${i}/60: Pods not ready yet (${READY_PODS}/${DESIRED_PODS}), waiting..."
            sleep 5
          done
          
          if [ "${READY_PODS}" != "${DESIRED_PODS}" ] || [ "${READY_PODS}" = "0" ]; then
            echo "ERROR: MariaDB operator pods not ready after 5 minutes"
            echo "Deployment status:"
            kubectl get ${OPERATOR_DEPLOYMENT} -n {{ .Release.Namespace }} -o yaml
            echo "Pod status:"
            kubectl get pods -n {{ .Release.Namespace }} -l app.kubernetes.io/name=mariadb-operator
            exit 1
          fi
          
          # Additional grace period for webhook to start
          echo "Waiting additional 10 seconds for webhook to initialize..."
          sleep 10
          
          # Find webhook service dynamically
          echo "Searching for MariaDB operator webhook service..."
          WEBHOOK_SERVICE=""
          for i in {1..30}; do
            WEBHOOK_SERVICE=$(kubectl get services -n {{ .Release.Namespace }} -o name | grep -i mariadb | grep -i webhook | head -1 | sed 's/service\///' || true)
            if [ -n "${WEBHOOK_SERVICE}" ]; then
              echo "Found webhook service: ${WEBHOOK_SERVICE}"
              break
            fi
            echo "Attempt ${i}/30: No webhook service found yet, waiting..."
            sleep 10
          done
          
          if [ -z "${WEBHOOK_SERVICE}" ]; then
            echo "ERROR: MariaDB operator webhook service not found after 5 minutes"
            echo "Available services:"
            kubectl get services -n {{ .Release.Namespace }} | grep -i mariadb
            exit 1
          fi
          
          # Wait for webhook service to have endpoints
          echo "Waiting for webhook service endpoints..."
          for i in {1..60}; do
            ENDPOINT_IP=$(kubectl get endpoints ${WEBHOOK_SERVICE} -n {{ .Release.Namespace }} -o jsonpath='{.subsets[0].addresses[0].ip}' 2>/dev/null || echo "")
            if [ -n "${ENDPOINT_IP}" ]; then
              echo "Webhook service has endpoints: ${ENDPOINT_IP}"
              break
            fi
            echo "Attempt ${i}/60: No endpoints yet, waiting..."
            sleep 5
          done
          
          if [ -z "${ENDPOINT_IP}" ]; then
            echo "ERROR: MariaDB operator webhook service has no endpoints after 5 minutes"
            echo "Service endpoints:"
            kubectl get endpoints ${WEBHOOK_SERVICE} -n {{ .Release.Namespace }} -o yaml
            echo "Service details:"
            kubectl get service ${WEBHOOK_SERVICE} -n {{ .Release.Namespace }} -o yaml
            exit 1
          fi
          
          # Test webhook connectivity (optional)
          echo "Testing webhook connectivity..."
          WEBHOOK_URL="https://${WEBHOOK_SERVICE}.{{ .Release.Namespace }}.svc:443"
          
          # Use a simple curl test to verify the webhook is responding
          # We expect a 404 or similar HTTP error, not a connection refused
          if curl -k --connect-timeout 10 --max-time 30 "${WEBHOOK_URL}/health" 2>/dev/null || \
             curl -k --connect-timeout 10 --max-time 30 "${WEBHOOK_URL}/" 2>/dev/null; then
            echo "Webhook is responding to HTTP requests"
          else
            echo "WARNING: Webhook not responding to HTTP requests, but endpoints exist"
            echo "This may be normal if the webhook only accepts specific validation requests"
          fi
          
          echo "MariaDB operator and webhook are ready!"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      serviceAccountName: {{ include "slurm.fullname" . }}-mariadb-wait
      {{- with .Values.slurm.controller.podSpec.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slurm.controller.podSpec.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slurm.controller.podSpec.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
