{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.nfs.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{ .Values.nfs.server.namespace }}
  labels:
    {{- include "slurm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nfs-server
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-server-claim
      restartPolicy: Always
      containers:
      - name: nfs-server
        image: {{ .Values.nfs.server.image.repository }}:{{ .Values.nfs.server.image.tag }}
        env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /nfsshare
            name: nfs-vol
        resources:
          {{- toYaml .Values.nfs.server.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: {{ .Values.nfs.server.namespace }}
  labels:
    {{- include "slurm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nfs-server
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
spec:
  ports:
    - name: nfs
      port: 2049
  selector:
    role: nfs-server
{{- end }}
