apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode-devcontainer.serviceName" . }}
  namespace: {{ .Values.global.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "vscode-devcontainer.deploymentName" . }}
  annotations:
    workspace.exalsius.ai/access-info: "true"
    workspace.exalsius.ai/access-type: "nodeport"
    workspace.exalsius.ai/protocol: "tcp"
    workspace.exalsius.ai/port-name: "ssh"
spec:
  type: NodePort
  ports:
    - port: 22
      name: ssh
      targetPort: 22
  selector:
    app: {{ include "vscode-devcontainer.deploymentName" . }}

