{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.nfs.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nfs.server.namespace }}
  labels:
    {{- include "slinky.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nfs-server
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
{{- end }}
