{{- if or .Values.sshPassword .Values.sshPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "devpod.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.sshPassword }}
  SSH_PASSWORD: {{ .Values.sshPassword | quote }}
  {{- end }}
  {{- if .Values.sshPublicKey }}
  SSH_PUBLIC_KEY: |
{{ .Values.sshPublicKey | indent 4 }}
  {{- end }}
{{- end }}
