apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "marimo.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKEN_PASSWORD: {{ .Values.tokenPassword | quote }}
