apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{ include "diloco-training.jobName" . }}
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    job-name: {{ include "diloco-training.jobName" . }}
spec:
  maxRetry: 3
  minAvailable: 2
  plugins:
    pytorch:
      - --master=master
      - --worker=worker
      - --port=23456
    svc: []
  queue: default
  schedulerName: volcano
  tasks:
    - maxRetry: 3
      minAvailable: 1
      name: master
      policies:
        - action: CompleteJob
          event: TaskCompleted
      replicas: 1
      template:
        metadata:
          annotations:
            scheduling.k8s.io/group-name: {{ include "diloco-training.jobName" . }}
          labels:
            job-name: {{ include "diloco-training.jobName" . }}
            role: master
        spec:
          containers:
            - command:
                - python
                - /app/diloco_training/training/start_training.py
              envFrom:
                - configMapRef:
                    name: {{ include "diloco-training.configmapName" . }}
              image: {{ .Values.deploymentImage }}
              imagePullPolicy: IfNotPresent
              name: master
              requests:
                cpu: {{ .Values.cpuCores }}
                memory: {{ .Values.memoryGb }}Gi
                nvidia.com/gpu: {{ .Values.gpuCount }}
                ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
              limits:
                cpu: {{ .Values.cpuCores }}
                memory: {{ .Values.memoryGb }}Gi
                nvidia.com/gpu: {{ .Values.gpuCount }}
                ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
          restartPolicy: OnFailure
          runtimeClassName: nvidia
    - maxRetry: 3
      minAvailable: {{ sub .Values.nodes 1 }}
      name: worker
      replicas: {{ sub .Values.nodes 1 }}
      template:
        metadata:
          annotations:
            scheduling.k8s.io/group-name: {{ include "diloco-training.jobName" . }}
          labels:
            job-name: {{ include "diloco-training.jobName" . }}
            role: worker
        spec:
          containers:
            - command:
                - python
                - /app/diloco_training/training/start_training.py
              envFrom:
                - configMapRef:
                    name: {{ include "diloco-training.configmapName" . }}
              image: {{ .Values.deploymentImage }}
              imagePullPolicy: IfNotPresent
              name: worker
              requests:
                cpu: {{ .Values.cpuCores }}
                memory: {{ .Values.memoryGb }}Gi
                nvidia.com/gpu: {{ .Values.gpuCount }}
                ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
              limits:
                cpu: {{ .Values.cpuCores }}
                memory: {{ .Values.memoryGb }}Gi
                nvidia.com/gpu: {{ .Values.gpuCount }}
                ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
              workingDir: /app
          restartPolicy: OnFailure
          runtimeClassName: nvidia
