{{- if .Values.modelRegistry.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-model-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-model-registry
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-model-registry
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-model-registry
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-model-registry
    namespace: {{ .Release.Namespace }}
{{- end }}
