apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "model-discovery-httproute"
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-inference-gateway
  rules:
    - backendRefs:
        - name: model-registry
          port: {{ .Values.modelRegistry.service.port }}
      matches:
        - path:
            type: PathPrefix
            value: /v1/models